### ISSUE TITLE
A few sections having errors

### ISSUE THREAD

**Issue by andypbrowne** [researchops/toolbox#60]
sections in multiple categories are not showing charts or data. Is it possible that some Airtable data changed and is breaking the charts on the front-end?

Please investigate these examples:

- [x] Participant scheduling
- [x] Heatmaps
- [x] Benchmark Testing
- [x] Heuristic evaluations
- [x] Surveys 
- [x] interviews
- [x] diary studies
- [x] focus groups

**Comment by d4rekanguok** [comment]
Hey @andypbrowne, there are 2 reasons why these fields aren't working:

- `Participant scheduling` appears to be commented out in the code https://github.com/researchops/toolbox/blob/f6b16d5cf4e0a89a66de1769d904b3c1201749c2/src/routes/participant-management.svx#L72
and also isn't listed in the loader on top of that page: 
https://github.com/researchops/toolbox/blob/f6b16d5cf4e0a89a66de1769d904b3c1201749c2/src/routes/participant-management.svx#L8

- Due to Airtable API shenanigans (it doesn't give us the field ID, from what I remember...) we decided to rely on the field names on Airtable to fetch data. It appears that some of these has been modified, for example `Heat map` was previously `Heat maps`. I've checked the DB & updated the fieldmap in #61 

---

This issue surfaces 2 weak points in the codebase, that we chose to do at the time for the sake of saving cost:
- Data must be synced with Airtable via **field name**, not field id (I think at the time getting field id requires access to a meta field that cost us more, need to check again)
- On the .md page where data is presented, it needs to be requested manually (in `create_loader`)

We need to upgrade the codebase to latest svelte-kit at some point, can revisit these then.
